### ISSUE TITLE
Bootstrap GraphQL Nexus

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/graphql-nexus#1]
GraphQL Nexus is a free to use nexus of GraphQL APIs powered by tailcall. 
The scope of this issue is to bootstrap the project using k8.

**Technical Requirements**
- Use **AWS** as our cloud platform.
- Setup service discovery using [Istio]
- Should support multiple deployment's of [tailcall] that are independently scalable.
- Should run the latest release version of [Tailcall].
- Each tailcall deployment will load configurations from a directory under `/integrations`. Starting with jsonplaceholder.
- Setup Envoy ingress, such that it should route traffic on different integrations. for eg: `/jsonplaceholder/graphql` should route traffic to tailcall running in dir `/integrations/jsonplaceholder`.
- An nginx based egress should be used as a reverse proxy. This should be used for rate-limiting and building a centralized http cache.
- Use [helm] to reduce duplication in configurations, packaging and templatizing the project.
- Use [pulumi] to setup AWS infrastructure.

[pulumi]:https://www.pulumi.com/
[Istio]:https://istio.io/
[Tailcall]:https://tailcall.run/
[helm]:https://helm.sh/

**Comment by SWAYAMKHANDURI** [comment]
/attempt#1
Not sure would be able to solve it but can try 

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clnmx0ayy0002mg0fa83icfsm/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by ayewo** [comment]
@tusharmath what cloud will be used to host the cluster? AWS?

**Comment by tusharmath** [comment]
We will fly.io 😇

**Comment by SWAYAMKHANDURI** [comment]
Hey there still working on the issue

**Comment by ayewo** [comment]
> We will fly.io 😇

@tusharmath that’s a very interesting choice, ✨. I think I still have a decent amount of unused credits there. I did some quick searches and it sounds like it _might work_. Some folks were able to use `k3s` on fly.

Unfortunately, Fly doesn’t have any official docs on how to do this.

Can you share info about what you have in mind?

**Comment by tusharmath** [comment]
I didn't realize that Fly doesn't talk much about K8. I guess, we can start with AWS in that case. We could use pulumi to set that up too. Will update the issue with these details.
Thanks @ayewo for bringing it up.

**Comment by ayewo** [comment]
Well, Fly's bread and butter is Docker and not k8s (though I found claims of people getting a subset of k8s to work i.e. k3s).

The `fly-cli` offers tooling to "dockerize" your app so that it is easy to deploy in their environment. For transparent proxying between multiple app/services they use Wireguard under the hood.

**Comment by tusharmath** [comment]
This is the problem with most PAAS operators. They make the hello world app so easy to deploy but working on production scale is just not that easy. They could have just supported kubernetes out of the box.

**Comment by ayewo** [comment]
Haha, yes. But let's be honest k8s is a monstrosity. It was designed for companies with needs approaching Google's scale. Only well-resourced teams with complex requirements should be reaching for k8s by default. 

Fly does have excellent support for Docker though 🙂.

**Comment by ayewo** [comment]
@tusharmath please assign me, thank you.

I can deploy to either AWS or Fly.io which was your original preference. But if you don't mind, I would like better understand your goals[^1] before I begin.

Mind if I ask you clarifying questions in Discord? 

[^1]: [Kubernetes Isn’t Always the Right Choice](https://thenewstack.io/kubernetes-isnt-always-the-right-choice/) hat tip to https://twitter.com/bibryam/status/1718242458771870045

**Comment by tusharmath** [comment]
@ayewo Putting a hold on this for now. I don't think we have the bandwidth to support it. Hope you haven't started on this just yet 🙏

**Comment by ayewo** [comment]
@tusharmath 
> Hope you haven't started on this just yet 🙏

Not started yet so thanks for the heads up. Please ping me when you do decide to move forward 🤞.

**Comment by ayewo** [comment]
@tusharmath 
Fly.io officially launched support for k8s today:  [Introducing Fly Kubernetes ](https://fly.io/blog/fks/).
